# Generated by Django 3.2.6 on 2021-08-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serve_url',
            name='uhash',
            field=models.CharField(default='', max_length=16),
        ),
    ]
